language: php
php:
  - 5.6
  - 5.5
  - nightly
  - hhvm
sudo: false
install:
  - mkdir runtime
  - composer self-update
  - composer install --dev --prefer-dist
  - composer update maslosoft/signalstest
script:
  - ./run-travis
