language: php
php:
  - 5.6
  - 5.5
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
install:
  - composer self-update
  - composer install --dev --prefer-dist
  - composer update maslosoft/signalstest
after_script:
  - wget --no-check-certificate https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --repository=g/Maslosoft/Signals --revision=`git rev-parse HEAD` --format=php-clover ./tests/_output/coverage.clover
script: vendor/bin/codecept run unit --coverage --html --coverage-html=. --coverage-xml=./coverage.clover