language: php
sudo: false
dist: trusty
php:
  - 5.6
  - 5.5
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php: nightly
cache:
  directories:
    - vendor
install:
  - bash -c 'if [ -e "vendor/maslosoft/signalstest" ]; then rm -rf "vendor/maslosoft/signalstest"; fi;'
  - composer update
  - composer install --dev --prefer-dist --no-interaction
before_script:
  - cd $TRAVIS_BUILD_DIR
script:
  - bash run-travis
