#!/bin/bash
rm -rf runtime/*
if [ "$TRAVIS_PHP_VERSION" == "hhvm" ] || [ "$TRAVIS_PHP_VERSION" == "nightly" ]; then
	vendor/bin/codecept run unit
	status=$?
fi;
if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then 
	vendor/bin/codecept run unit --coverage --html --coverage-html=. --coverage-xml=./coverage.clover
	status=$?
fi;
if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then
	wget --no-check-certificate https://scrutinizer-ci.com/ocular.phar
	php ocular.phar code-coverage:upload --revision=`git rev-parse HEAD` --format=php-clover ./tests/_output/coverage.clover
fi;
rm ocular.phar
echo "$status"
exit $status